
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: survey-deployment
  labels:
    app: survey
spec:
  replicas: 3
  selector:
    matchLabels:
      app: survey
  template:
    metadata:
      namespace: default
      labels:
        app: survey
    spec:
      containers:
      - name: survey
        image: nannredd/studentsurvey:latest
        ports:
        - containerPort: 8080
